host: 127.0.0.1
http:
  port: 8081
mongo:
  url: "test.mongodb.net/"
  database: "testDB"
  username: "test"
  password: "test"
kafka:
  enabled: false
  topic: "reservation"
  topic_prefix: ""
  partition: 0
  username: "test"
  password: "test"
  brokers:
    - "adress 1"
    - "adress 2"
