// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "API Healthcheck",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/reservation": {
            "get": {
                "description": "Get all reservations",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/model.Reservation"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.GuestNeed": {
            "type": "object",
            "properties": {
                "dietaryRequirements": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "foodPreferences": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "guestName": {
                    "type": "string"
                },
                "remark": {
                    "type": "string"
                }
            }
        },
        "model.Reservation": {
            "type": "object",
            "properties": {
                "dateTimeSlotId": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "guestCount": {
                    "type": "integer"
                },
                "guestNeeds": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.GuestNeed"
                    }
                },
                "id": {
                    "type": "string"
                },
                "isCancelled": {
                    "type": "boolean"
                },
                "isRescheduled": {
                    "type": "boolean"
                },
                "lastName": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "remark": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
