name: Docker

on:
  workflow_run:
    workflows: ["Datetime CI","Reservation CI","Config CI"]
    branches: [master]
    types:
      - completed

jobs:
  docker:
    environment: docker
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.TOKEN }}
      - name: Build and push Reservation
        uses: docker/build-push-action@v2
        with:
          push: true
          context: "{{defaultContext}}:src/reservation_api"
          tags: resit2022/reservation:latest
      - name: Build and push Config
        uses: docker/build-push-action@v2
        with:
          push: true
          context: "{{defaultContext}}:src/config_api"
          tags: resit2022/config_api:latest
      - name: Build and push Datetime
        uses: docker/build-push-action@v2
        with:
          push: true
          context: "{{defaultContext}}:src/datetime_api"
          tags: resit2022/config_api:latest
      
